messages:
    NOT_YET_IMPLEMENTED: "This portal type is not yet implemented."
    NO_LONGER_IMPLEMENTED: "This portal type has been removed from the game."
    REQUIRE_EMPTY_INVENTORY: "Your inventory must be empty to use this portal."
    PORTAL_NOT_LINKED: "This portal is not yet linked."
    SUBSCRIBER_ONLY_PORTAL: "You must be a subscriber to use this portal."
portal:
    touch_timeout: 3
    portal_timeout: 3
    shared_cooldown: 30
world:
    nether:
        world: world_nether
        world_nether: world
        new_highridge: new_nether
        new_nether: new_highridge
        world_the_end: new_highridge
    end:
        world: world_the_end
        world_nether: world_the_end
        new_highridge: world_the_end
        new_nether: world_the_end
        world_the_end: new_highridge
db:
    provider: minecarts