name: PortalForge
main: com.minecarts.portalforge.PortalForge
version: ${pom.version}
website: http://minecarts.com
author: Verrier
depend: [DBConnector]
description: >
             A custom portal creation, destruction, and detection plugin
commands:
    portal:
        description: Access the portal menu
        usage: "/<command> [create], [dest (#)|exit (#)], [vel|velocity <speed>], [edit #], [done|save], [debug], [info #], [delete #], [use #], [clear|cache #], [goto #]"
permissions:
    portalforge.*:
        description: "Gives access to all PortalForge functionality"
        children:
            portalforge.ignite: true
            portalforge.use: true
            portalforge.debug: true
            portalforge.admin: true
    portalforge.ignite:
            description: "Allows igniting of portals"
            default: true
    portalforge.use:
            description: "Allow player to use a portal"
            default: true
    portalforge.debug:
            description: "Display debugging output when using portals"
            default: op
    portalforge.admin:
            description: "Allow access to administration commands for portals"
            default: op