name: PortalForge
main: com.minecarts.portalforge.PortalForge
version: ${pom.version}
website: http://minecarts.com
author: Verrier
depend: [DBConnector]
description: >
             A custom portal creation, destruction, and detection plugin
commands:
  portal:
    description: Access the portal menu
    usage: "/<command> [create], [dest (#)|exit (#)], [vel|velocity <speed>], [edit #], [done|save], [debug], [info #], [delete #], [use #], [clear|cache #]"