name: PortalForge
main: com.minecarts.portalforge.PortalForge
version: 1.0.0
website: http://minecarts.com
author: Verrier
description: >
             A custom portal creation, destruction, and detection plugin
commands:
  portal:
    description: Access the portal menu
    usage: "/<command> [create], [dest|exit], [vel|velocity <speed>], [edit #], [done|save], [debug], [info #], [delete #]"